### PR TITLE
Made link color variable name more descriptive

### PR DESCRIPTION
**Pull request by michealp-coder**
Replaced '--color' variable name with '--color-link' to make the variable name more descriptive.

### CODE REVIEW

**Comment by andybrewer** [comment]
This is a good idea, thank you! It's also a breaking change, so I'll save it for a major version bump.

**Comment by michealp-coder** [comment]
One thing to note, the table header was set to the same color as a link. So I changed the table header to just be the color of text.

I'm not sure that's what you'd want but I was of the mindset that the color of a link is normally unique on the page.

**Comment by andybrewer** [comment]
Right, I noticed that. I'll play around with it to see, but another option would be a `--color-table` variable.

**Comment by andybrewer** [comment]
I decided to leave `--color` in for v1.X, but will plan to remove it in v2. I included your suggestion in the latest release: https://github.com/andybrewer/mvp/releases/tag/v1.8

Thanks!

**Pull request closed without merging**
