### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by aembleton**

### CODE REVIEW

**Review by andybrewer — APPROVED** [review]
Awesome -- love it!

**Comment by andybrewer** [comment]
@aembleton - I commented out dark mode because I couldn't get it to look good with the logo / images on the site. But at least those that want it can uncomment it easily. Thanks again!

**Comment by jimmywarting** [comment]
Would love it if this where enabled on your web page so it's easy to preview how it looks like, a toggle would be grate too.

**Comment by andybrewer** [comment]
@jimmywarting is it possible to do force dark mode through JavaScript? I think you can only detect if it's enabled in the browser or not.

**Comment by jimmywarting** [comment]
A simple class that you can toggle would do it?

```css
body.darkMode {
        --color: #0097fc;
        --color-accent: #0097fc4f;
        --color-bg: #333;
        --color-bg-secondary: #555;
        --color-link: #0097fc;
        --color-secondary: #e20de9;
        --color-secondary-accent: #e20de94f;
        --color-shadow: #bbbbbb20;
        --color-table: #0097fc;
        --color-text: #f7f7f7;
        --color-text-secondary: #aaa;
}
```

**Comment by andybrewer** [comment]
Yes, but I don't want to clutter MVP.css with classes

**Comment by jimmywarting** [comment]
then only add it to your demo website with a style object or something?

**Comment by andybrewer** [comment]
@jimmywarting Good idea, I was overthinking it :)

It's live here: https://andybrewer.github.io/mvp/

**Comment by jimmywarting** [comment]
LuL, the reason why i asked for it was b/c some device i used did not have prefer color = dark, or i wanted to see how it looked like when it was in light mode.

But now on i'm on a device that has prefer dark color on by default, so even if i toggle now on the website it's always dark 😅 
guess it needs a toggle between light/dark and not dark/undefined :P

**Comment by jimmywarting** [comment]
There are also ways you can change css variables using javascript (think it was something with style.setProperty() or something )

**Comment by andybrewer** [comment]
Good catch! I added some JS to detect if Dark Mode is currently on and then adjust the toggle appropriately. Does that work for you now? https://andybrewer.github.io/mvp/

**Pull request merged**
