### PR TITLE
Adding Figmage to the showcase

### PR DESCRIPTION
**Pull request by rlingineni**
I've been running Figmage for over a year now, just wanted to add it to the showcase. 

Love the library. It's been a great library to quickly put-up websites with more focus on the copy and less on the design

### CODE REVIEW

**Comment by ChristopherBilg** [comment]
> To submit your site built with MVP.css create a pull request or an issue. For pull requests, please keep sites in alphabetical order.

**Comment by rlingineni** [comment]
Wait, this is a pull request right? Not sure what I'm missing

Edit: I see, the site isn't alphabetical. I can fix that. Thanks

**Comment by andybrewer** [comment]
> Edit: I see, the site isn't alphabetical. I can fix that. Thanks

Thanks, let me know when it's fixed.

**Comment by rlingineni** [comment]
@andybrewer - fixed

**Review by andybrewer — APPROVED** [review]

**Pull request merged**
