### PR TITLE
Adjustable scrollbar color

### PR DESCRIPTION
**Pull request by maartenpaauw**
This pull request introduces the capability to customize the color of the scrollbar by overriding the `--color-scrollbar` variable.

### CODE REVIEW

**Review by ChristopherBilg — APPROVED** [review]
I like it! Great addition

**Comment by ChristopherBilg** [comment]
@andybrewer I believe we have a handful of changes since the last release.

**Comment by andybrewer** [comment]
Sounds good. Do you want to make a new release?

**Comment by ChristopherBilg** [comment]
You got it, I'll get it prepped and ping you to release to CDNs.

**Comment by ChristopherBilg** [comment]
Alright, the release is ready for v1.15.

**Comment by andybrewer** [comment]
Awesome, thanks! Deployed to NPM.

Feel free to create a new GitHub Release as well. I like how you've done
the last couple where you noted new contributors.

Thanks!

Andy Brewer

**Pull request merged**
