### PR TITLE
Add Dropdown Styling for Nav Menus

### PR DESCRIPTION
**Pull request by DennisSuitters**
This PR adds styling without classes to allow for Dropdown Menu's in `<nav/>` elements.

Screenshot from 2020-04-01 12-21-45

### CODE REVIEW

**Comment by DennisSuitters** [comment]
I added relevant markup to the `mvp.html` example file. And updated a couple of the style attributes to properly use the `var(--)` attributes.

**Comment by andybrewer** [comment]
Thanks @DiemenDesign! I tweaked it slightly and added it to v1.3. Appreciate the contribution :)

**Comment by DennisSuitters** [comment]
No problem, at the least it gave some idea's, glad your able to use it in some way.

**Comment by andybrewer** [comment]
I used almost all of it! I just couldn't get the drop-down link text to left align until I modified a line or two, but then it worked like a charm. Thanks again for contributing!

**Pull request closed without merging**
